### ISSUE TITLE
Remove self.authenticate variable

### ISSUE THREAD

**Issue by alastair** [trompamusic/tpc#11]
The [`self.authenticate`](https://github.com/trompamusic/tpl/blob/dc24adc40b64026e5d7879884f7062cfc71866bc/tpl/application.py#L91) field is set to the value of the trompace-client config option and passed in to `trompace.connection.submit_query`, however this isn't required. submit_query will automatically skip authentication if the config option is set.
The auth_required argument should be set to True for all mutations in the TPL.

**Comment by aggelosgkiokas** [comment]
updated in dev branch
