### ISSUE TITLE
local data path should be configured at tpl-level, not algorithm level

### ISSUE THREAD

**Issue by alastair** [trompamusic/tpc#4]
Currently `self.data_path` is filled in by a section
```
[data]
path = /home/aggelos/bin/tpl/data/
```
in the config file of the Entrypoint that is being run. This is a config option that should be relevant to the TPL, not each algorithm that is being run in it.

I think it'd be a good idea to add a separate configuration for global TPL options. I think something similar might have already existed, looking at the config/tpl.ini file.

For a temporary directory to put input/output data we could use `os.mkstemp` to generate a random temporary directory, or we could specify a data directory and generate a specific directory per entrypoint (perhaps based on its id?)

**Comment by alastair** [comment]
It'd be a good idea to add this to the `--connection` config file, instead of the `--app` config file.

Another small point here - I think it'd be better to separate the config files for the trompace client and the tpl into different files. Sharing the same content between two different libraries feels like it has the potential to cause confusion and problems in the future

**Comment by aggelosgkiokas** [comment]
Sovled. The data path is on the tpl.ini. All connection information is containted in a connection.ini file path, which is also containted in the tpl.ini
