### ISSUE TITLE
add installation dependencies to setup.py

### ISSUE THREAD

**Issue by alastair** [trompamusic/tpc#6]
In python, if you want to install something with `pip install x` you should add its dependencies to `install_requires` in setup.py. Sometimes it makes sense to do this by just reading the contents of requirements.txt, e.g. https://github.com/metabrainz/brainzutils-python/blob/ff8592ddaf27db6b1abc521b22c5893e9e931120/setup.py#L14

we should update the README.md file to indicate how to install with setup.py install or with requirements.txt depending on the requirements.

**Comment by aggelosgkiokas** [comment]
fixed in the current dev version
